services:
    simple_bus.asynchronous.message_envelope_factory:
        alias: simple_bus.asynchronous.default_message_envelope_factory

    simple_bus.asynchronous.default_message_envelope_factory:
        class: SimpleBus\Asynchronous\Message\Envelope\DefaultMessageEnvelopeFactory
        public: false
