services:
    register_user_handler:
        class: Domain\Command\RegisterUserHandler
        arguments:
            - @user_repository
            - @event_recorder
        tags:
            - { name: command_handler, handles: register_user }

    user_repository:
        class: Infrastructure\Persistence\Doctrine\DoctrineUserRepository
        arguments:
            - @doctrine

    when_user_was_registered_send_welcome_email_event_subscriber:
        class: Domain\Event\WhenUserWasRegisteredSendWelcomeEmail
        arguments:
            - @user_repository
            - @mailer
        tags:
            - { name: asynchronous_event_subscriber, subscribes_to: user_was_registered }

    register_user_console_command:
        class: Infrastructure\Cli\RegisterUserConsoleCommand
        tags:
            - { name: console.command }

    user_controller:
        class: Infrastructure\Web\UserController
        calls:
            - [setContainer, [@service_container]]

    create_user_form_type:
        class: Infrastructure\Web\CreateUserType
        arguments:
            - @user_repository
        tags:
            - { name: form.type, alias: create_user }