services:
    register_user_handler:
        class: Traditional\Bundle\UserBundle\Command\RegisterUserHandler
        arguments:
            - @doctrine
            - @event_recorder
        tags:
            - { name: command_handler, handles: register_user }

    user_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - Traditional\Bundle\UserBundle\Entity\User

    when_user_was_registered_send_welcome_email_event_subscriber:
        class: Traditional\Bundle\UserBundle\Event\WhenUserWasRegisteredSendWelcomeEmail
        arguments:
            - @user_repository
            - @mailer
        tags:
            - { name: event_subscriber, subscribes_to: user_was_registered }